includes:
  - ../base.yaml
dataset:
  dataset_name: GDMotif
model:
  model_layer: 3
  global_pool: mean
train:
  lr: 0.001
  max_epoch: 100
  train_bs: 512
  val_bs: 512
  test_bs: 512
  weight_decay: 0.
