name: UniGOOD
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.7=py38ha9d4c09_0
  - brotli-python=1.0.9=py38hfa26641_7
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.3.1=ha36c431_9
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - googledrivedownloader=0.4=pyhd3deb0d_1
  - idna=3.8=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.8.4=py38hc78ab66_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.14=h5eee18b_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.0.3=py38h1128e8f_0
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - pyg=2.0.3=py38_torch_1.10.0_cu113
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.19=h955ad1f_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-louvain=0.16=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.1=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-cluster=1.6.0=py38_torch_1.10.0_cu113
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.0.9=py38_torch_1.10.0_cu113
  - pytorch-sparse=0.6.13=py38_torch_1.10.0_cu113
  - pytorch-spline-conv=1.2.1=py38_torch_1.10.0_cu113
  - pyyaml=6.0=py38h0a891b7_4
  - readline=8.2=h5eee18b_0
  - scikit-learn=1.3.0=py38h1128e8f_1
  - scipy=1.10.1=py38hf6e8229_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.10.1=py38_cu113
  - torchvision=0.11.2=py38_cu113
  - typing_extensions=4.11.0=py38h06a4308_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - aiohappyeyeballs==2.4.0
    - aiohttp==3.10.5
    - aiosignal==1.3.1
    - alabaster==0.7.13
    - aliyun-python-sdk-core==2.16.0
    - aliyun-python-sdk-kms==2.16.5
    - antlr4-python3-runtime==4.9.3
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==24.2.0
    - babel==2.16.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.3
    - cachetools==5.5.0
    - captum==0.2.0
    - cffi==1.17.1
    - cilog==1.2.3
    - click==8.1.8
    - cloudpickle==3.0.0
    - coverage==7.6.1
    - crcmod==1.7
    - cryptography==45.0.6
    - cvxopt==1.3.2
    - cycler==0.12.1
    - cython==3.0.11
    - decorator==5.1.1
    - delu==0.0.25
    - dive-into-graphs==1.1.0
    - docutils==0.17.1
    - einops==0.8.1
    - et-xmlfile==1.1.0
    - execnet==2.1.1
    - executing==2.1.0
    - faiss-gpu==1.7.2
    - filelock==3.14.0
    - fonttools==4.53.1
    - frozenlist==1.4.1
    - fsspec==2024.9.0
    - gdown==5.2.0
    - google-auth==2.34.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.66.1
    - h5py==3.11.0
    - hydra-core==1.3.2
    - imageio==2.35.1
    - imagesize==1.4.1
    - importlib-metadata==8.4.0
    - importlib-resources==6.4.4
    - iniconfig==2.0.0
    - ipython==8.12.3
    - isodate==0.6.1
    - jedi==0.19.1
    - jmespath==0.10.0
    - kiwisolver==1.4.7
    - lightning-utilities==0.11.7
    - littleutils==0.2.4
    - llvmlite==0.41.1
    - markdown==3.7
    - markdown-it-py==3.0.0
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mmcv==1.3.8
    - mmengine==0.10.7
    - model-index==0.1.11
    - mpmath==1.3.0
    - multidict==6.0.5
    - munch==2.5.0
    - mypy-extensions==1.0.0
    - networkx==2.8
    - numba==0.58.0
    - numpy==1.21.6
    - oauthlib==3.2.2
    - ogb==1.3.6
    - omegaconf==2.3.0
    - openmim==0.3.9
    - ordered-set==4.1.0
    - oss2==2.17.0
    - outdated==0.2.2
    - parso==0.8.4
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pluggy==1.5.0
    - prompt-toolkit==3.0.47
    - protobuf==3.20.1
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - py==1.11.0
    - pyasn1==0.6.0
    - pyasn1-modules==0.4.0
    - pycparser==2.22
    - pycryptodome==3.23.0
    - pygments==2.18.0
    - pynndescent==0.5.13
    - pynvml==11.5.3
    - pyscf==2.6.2
    - pytest==7.1.2
    - pytest-cov==3.0.0
    - pytest-forked==1.6.0
    - pytest-xdist==2.5.0
    - pytorch-lightning==1.9.0
    - pytz==2023.4
    - pywavelets==1.4.1
    - rdflib==7.0.0
    - rdkit-pypi==2022.9.5
    - requests==2.28.2
    - requests-oauthlib==2.0.0
    - rich==13.4.2
    - rsa==4.9
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.8
    - scikit-image==0.19.1
    - seaborn==0.13.2
    - setuptools
    - shap==0.44.1
    - slicer==0.0.7
    - snowballstemmer==2.2.0
    - soupsieve==2.6
    - sphinx==5.3.0
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - stack-data==0.6.3
    - sympy==1.13.2
    - tabulate==0.9.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.4.0
    - texttable==1.7.0
    - tifffile==2023.7.10
    - tomli==2.0.1
    - torchmetrics==1.4.1
    - torchsampler==0.1.2
    - tqdm==4.64.0
    - traitlets==5.14.3
    - typed-argument-parser==1.7.2
    - typing-inspect==0.9.0
    - umap-learn==0.5.7
    - urllib3==1.26.20
    - vector-quantize-pytorch==1.0.7
    - wcwidth==0.2.13
    - werkzeug==3.0.4
    - yapf==0.43.0
    - yarl==1.9.11
    - zipp==3.20.1
