includes:
  - base.yaml
task: pretrain
model:
  model_name: UniGOODvGIN
  dropout_rate: 0
ood:
  ood_alg: UniGOOD
  ood_param: 0.7
  extra_param:
    - 1 # l
    - 1 # u
    - 10
    - 1
    - 1
    - 1
  wild_data: true
train:
  max_epoch: 100
  lr: 0.0001
  weight_decay: 0.0
log_file: exp_0
clean_save: true
